name: Rust Build & Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release project
        run: cargo build --release

      - name: Archive release files
        run: |
          cd target/release
          7z a ../../release_files.zip ./*

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello_rust-windows-release
          path: release_files.zip
